//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SimpleDataBase : DbContext
    {
        public SimpleDataBase()
            : base("name=SimpleDataBase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<SubjectGroup> SubjectGroup { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<MarketPlace> MarketPlace { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<UserToCourse> UserToCourse { get; set; }
    }
}
